version: 2

updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      time: '05:00'
      timezone: UTC
    labels:
      - 'type: improvement'
      - 'scope: code'
      - 'scope: deps'
    commit-message:
      prefix: 'feat'
      include: 'scope'
    open-pull-requests-limit: 30
