#!/usr/bin/env bash

set -euo pipefail

[ "${BASH_VERSINFO:-0}" -ge 4 ] || {
  echo "bash version 4 or higher is required" >&2
  exit 1
}

(
  cd research/ollama &&
  git submodule deinit -f llm/llama.cpp/ggml &&
  git submodule deinit -f llm/llama.cpp/gguf
)
